name: A207F VBMeta Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3 tar

      - name: Clone AVB tool
        run: |
          git clone https://android.googlesource.com/platform/external/avb

      - name: Build VBMeta (blank safe method)
        run: |
          cd avb
          python3 avbtool.py make_vbmeta_image \
          --output vbmeta.img

      - name: Create Odin TAR
        run: |
          tar -cvf vbmeta.tar avb/vbmeta.img

      - name: Upload VBMeta
        uses: actions/upload-artifact@v4
        with:
          name: vbmeta-A207F
          path: vbmeta.tar
